### PR TITLE
Update compositionEndedAt when composition cleared manually

### PR DESCRIPTION
**Pull request by KentoMoriwaki**
https://github.com/ProseMirror/prosemirror/issues/1190

### CODE REVIEW

**Comment by marijnh** [comment]
The assumption in the current code is that the browser will still fire a compositionend event after we force an end to it like this. Are you running into situations where that doesn't happen?

**Comment by KentoMoriwaki** [comment]
@marijnh Thanks for reviewing!

A compositionend event will be fired, but it does not update `view.compositionEndedAt` because `view.composing` already set to false in the `clearComposition`.

https://github.com/ProseMirror/prosemirror-view/blob/63aebf43770480659ab4a84b406263548f30dc42/src/input.js#L450-L456

Another solution would be to eliminate the `if (view.composing)` condition in the compositionend handler. Would that be better?

**Comment by marijnh** [comment]
Ah, right, good point, that makes sense. Always setting `composition` and `compositionEndedAt` together as in your patch seems reasonable.

A remaining issue is that IE doesn't have `CustomEvent`. Can you replace that with a `document.createEvent`/`event.initEvent`-based solution? (Or maybe there's another simpler way to get an event timestamp, I'm not sure.)

**Comment by KentoMoriwaki** [comment]
I updated to handle cross browser. CompositionEvent constructor is supported by IE. https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent/CompositionEvent#browser_compatibility

**Comment by marijnh** [comment]
Are you sure that's not just a mistake in MDN? Because the other events (see for example [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent#browser_compatibility) explicitly mention that the constructor form isn't supported by IE (thus the need for `createEvent`+`initEvent`).

**Comment by KentoMoriwaki** [comment]
You're right. I tested on IE and fixed it. (we don't need `initEvent` to get timeStamp)

**Comment by marijnh** [comment]
Hm, sorry to continue nitpicking, but (pre-Webkit) Edge browsers will also have `browser.ie` set, and may have adjusted to what other browsers are doing far enough to _not_ have `createEvent` set the timestamp (`createEvent` exists on modern browsers as well, but doesn't set a timestamp yet, leaving that to `initEvent`). I'd prefer a single path for all browsers that just calls both `createEvent` and `initEvent` to be sure.

**Comment by KentoMoriwaki** [comment]
Sorry for the late reply. I updated. How about this?

**Comment by marijnh** [comment]
> I'd prefer a single path for all browsers that just calls both createEvent and initEvent to be sure.

I still do. Those functions are available in all browsers, and also used in the keyboard-event-faking logic for Android, so just use them directly.

**Comment by marijnh** [comment]
Thanks!

**Pull request merged**
