### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by rev-hikari**

### CODE REVIEW

**Comment by marijnh** [comment]
This code provides a way for people to target CSS to a focused editor, and as such is _not_ unnecessary.

**Comment by rev-hikari** [comment]
Adding and removing class `ProseMirror-focused` is done in [input.js](https://github.com/ProseMirror/prosemirror-view/blob/33fe4a8/src/input.js#L542-L554), just like what `ProseMirror-hideselection` does (in [selection.js](https://github.com/ProseMirror/prosemirror-view/blob/33fe4a8/src/selection.js#L211-L216)).

Such logic in `computeDocDeco` is unnecessary, and may have some performance overhead (more frequent diffs in [viewdesc.js](https://github.com/ProseMirror/prosemirror-view/blob/33fe4a8/src/viewdesc.js#L857-L864)).

**Comment by rev-hikari** [comment]
Another problem is, `computeDocDeco` will not be called each time `view.focused` changed. That means, checking `view.focused` here is unreliable, and developers can't use `props.attributes` to customize focused class on editor.

**Comment by marijnh** [comment]
I believe that's why the code you removed is there. Can you come up with a situation where the focused class will go out of sync with the editor's focus status with the current code?

**Comment by rev-hikari** [comment]
`computeDocDeco` will be called each time `view.state` changed, but focus / blur the editor (without modify selection) doesn't make any changes on the editor state.

**Comment by marijnh** [comment]
Right, that's why there are separate class-toggling calls in the focus/blur handlers.

**Comment by rev-hikari** [comment]
No, it doesn't overwrite existing class names, `class` attribute is processed separately in [`patchAttributes`](https://github.com/ProseMirror/prosemirror-view/blob/33fe4a8/src/viewdesc.js#L857-L864). It will find the difference between current and previous class attribute returned by the decoration, and apply it to the dom.

**Comment by marijnh** [comment]
I see. I've merged this as da4b311

**Pull request closed without merging**
