### PR TITLE
Update domchange.js

### PR DESCRIPTION
**Pull request by XuXuDev**
Fix Chinese input method collaborative content is not correct

### CODE REVIEW

**Comment by XuXuDev** [comment]
Hello marijnh 
    I am a developer from China. I found a problem with a prosemirror cooperating under the Chinese input method.
    This problem will happen in this situation：
     1. Two people open this link : http://prosemirror.net/examples/collab/#edit-Example
    2.First person edit like this, but not press Space
image
    3.Another person do same thing
image
    4.First person press Space then second person press Space，we get the wrong result
image

    This is beacase domchange.js caculate "to" is wrong

**Comment by marijnh** [comment]
Thanks for looking into this. Does setting `to` to `Math.max(from, mapping.map(change.endA, -1))` also solve the problem for you? I think that'd be more correct.

**Comment by XuXuDev** [comment]
yes, this is also work!
thanks!

**Comment by XuXuDev** [comment]
I re-submitted a Pullrequest！
Thanks for the support

**Pull request closed without merging**
