### PR TITLE
Fix wrong step on backspace for ambiguous content

### PR DESCRIPTION
**Pull request by torifat**
Closes ProseMirror/prosemirror#726

### CODE REVIEW

**Comment by marijnh** [comment]
Looks great! Can you add a test? (I think what would work well is to add it to `test/test-domchange.js` and have a test that does two deletions like this, one with `lastKeyCode` set to 8, and one with it set to something else.)

Also, it may be worth resetting `lastKeyCode` after each change, or keeping a time counter with it and ignoring it if it's too old, to avoid spurious effects when a non-key-related change happens after a backspace press.

**Comment by torifat** [comment]
Yes, I can. I actually tried to add a test to `test/test-domchange.js` but didn't because the output is same. I didn't think about setting `lastKeyCode` manually though. Thanks for the suggestion.

I was also worried about unwanted states. So, I manually tried <kbd>Shit + Backspace</kbd>, <kbd>Ctrl + Backspace</kbd>, etc. Keeping a time counter is a great idea, it didn't occur to me.

**Comment by torifat** [comment]
I tried to incorporate your suggested changes. Let me know if you have any opinion about them 😃

**Comment by marijnh** [comment]
Thanks for following up! I've merged your work as eb194674f5095f and followed up with 0398b2b4076330de to make it work for ambiguous ctrl-backspace. The changes have been released as prosemirror-view 1.0.3

**Comment by torifat** [comment]
Thanks for the release. Don't know why didn't I think about `dispatchTransaction` 🤦‍♂️

**Pull request closed without merging**
