### PR TITLE
Fix Chinese input problem

### PR DESCRIPTION
**Pull request by XuXuDev**
Fix Chinese input method collaborative content is not correct

### CODE REVIEW

**Comment by XuXuDev** [comment]
I re-submitted a PullRequest at here.
thks

**Comment by XuXuDev** [comment]
Because we are all collaborative editors in Chinese.
Can U send a new version as 1.8.5?
thanks!

**Comment by marijnh** [comment]
Thanks. Merged and released as 1.8.5.

As an aside, this code will be superseded again in the near future by the 1.9 release (in the `composition` branch), which fixed this issue in a different way.

**Comment by XuXuDev** [comment]
Yes, we will conduct more tests in the Chinese environment, and will continue to pay attention to your progress, hope to maintain communication and make a contribution to prosemirror!

**Pull request merged**
