### PR TITLE
Let docViewDesc be a customNodeViewDesc

### PR DESCRIPTION
**Pull request by kapouer**
Please squash the commits i had some indentation issue.

### CODE REVIEW

**Comment by marijnh** [comment]
This doesn't really seem to follow the contract for custom node views—the dom node has already been allocated, whereas custom views get to create their own DOM. Also, the doc isn't at position 0, its _content_ starts at position 0. In general, the top node plays a different role than its content nodes, and trying to treat it the same is problematic.

**Comment by kapouer** [comment]
Okay ! surely i did not figure out how to make prosemirror properly ignore when specific dom nodes are added. My first try was with `ignoreMutation` because every block node has a custom nodeView in my setup - and this fails when it comes to childNodes of the root dom node.

**Comment by marijnh** [comment]
> and this fails when it comes to childNodes of the root dom node.

What kind of child nodes are these?

**Comment by kapouer** [comment]
Typically a div node added by https://github.com/wilddeer/stickyfill.

**Pull request closed without merging**
