### PR TITLE
Add necessary devDependencies for script test-server

### PR DESCRIPTION
**Pull request by MagnetoLee**
Add necessary devDependencies for script test-server

### CODE REVIEW

**Comment by marijnh** [comment]
Where are these used in the tests?

**Comment by MagnetoLee** [comment]
After clone and npm install, when npm run test-server will get this

image

I'm not sure what happened but can fixed by add devDependencies.

**Comment by MagnetoLee** [comment]
After clone and npm install, when npm run test-server will get this

image

I'm not sure what happened but can fixed by add devDependencies.

**Comment by marijnh** [comment]
That appears to be going through prosemirror-test-builder, which has these packages specified as peer dependencies. Which version of npm are you using to install the packages?

**Comment by MagnetoLee** [comment]
6.4.1
I will close it, thanks.

**Pull request closed without merging**
