### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by 4-1-1**
able to get new state after dispatch

### CODE REVIEW

**Comment by marijnh** [comment]
Doesn't reading `view.state` after calling dispatch already provide this?

**Comment by 4-1-1** [comment]
Any idea to make it without reading `view.state` ?

**Comment by jljorgenson18** [comment]
@4-1-1 Why not just do

```js
          const to =
            $to.pos - $to.parentOffset + path2[path1.length - 3].content.size;
          tr.setSelection(TextSelection.create(state.doc, from, to);
          const content = tr.selection.content();
          const stringContent = stringifyContent(
            content.content,
            isInCode(tr) // Assuming this could take a transaction or a selection object instead
          );
          const node = schema.nodes[type].create(
            {},
            schema.text(stringContent)
          );
          dispatch(tr.replaceSelectionWith(node));
```

**Comment by marijnh** [comment]
Or, if this is a command, read the third argument (the view).

**Comment by 4-1-1** [comment]
thanks a lot. It seems like a better way. 
and I close it. @jljorgenson18 @marijnh

**Pull request closed without merging**
