### PR TITLE
Use `::` to signify pseudo element

### PR DESCRIPTION
**Pull request by amk221**
Not strictly necessary, but adds clarity imo

### CODE REVIEW

**Comment by marijnh** [comment]
That's not a style rule this project uses, so I'm passing on this PR.

**Comment by amk221** [comment]
No worries, thanks for reviewing!

Can you elaborare on 
> That's not a style rule this project use

**Comment by marijnh** [comment]
The preference for `::` is not something I'm doing in the css files for ProseMirror. I also wouldn't accept a PR adding semicolons to the JavaScript files or similar.

**Comment by amk221** [comment]
Alrighty 🙂

Just to make sure we're on the same page:

From MDN
> As a rule, double colons (::) should be used instead of a single colon (:). This distinguishes pseudo-classes from pseudo-elements

**Pull request closed without merging**
