### PR TITLE
Support auto scroll while dragging on safari and improve the scroll interaction on other browsers

### PR DESCRIPTION
**Pull request by percy507**

### CODE REVIEW

**Comment by percy507** [comment]
https://github.com/ProseMirror/prosemirror/issues/1339

**Comment by marijnh** [comment]
This will leak event handlers and interfere with all drag events on the page, it seems.

**Comment by percy507** [comment]
True. I make an another commit to solve this. https://github.com/ProseMirror/prosemirror-view/pull/148/commits/718808471c892bf1d51aa28609db93f6f469f4e5

**Comment by marijnh** [comment]
Sorry, this still feels too messy to merge. There might be other drop targets next to the editor, in which case scrolling the editor when dragging something near it seems inappropriate. This could be implemented as a plugin, without modifying the editor core. And since most browsers do this natively already, I don't think it's worth adding extra, potentially problematic code to the library for.

**Comment by percy507** [comment]
It's ok. The code of this PR may inspire someone who face same problem.

**Pull request closed without merging**
